export interface Question {
  id: string;
  type: "technical" | "hr" | "coding";
  category: string;
  title: string;
  description: string;
  difficulty?: "easy" | "medium" | "hard";
  answer?: string;
}

export const sampleQuestions: Question[] = [
  {
    id: "tech-1",
    type: "technical",
    category: "React",
    title: "What is the Virtual DOM?",
    description: "Explain the concept of Virtual DOM in React and how it improves performance.",
    answer: "The Virtual DOM is a lightweight JavaScript representation of the actual DOM. React maintains a virtual DOM tree in memory and uses a diffing algorithm to compare it with the real DOM. When state changes occur, React creates a new virtual DOM tree, compares it with the previous one, and calculates the minimal set of changes needed. Only these specific changes are then applied to the real DOM, which is much faster than manipulating the entire DOM directly. This optimization significantly improves performance, especially in complex applications with frequent updates.",
  },
  {
    id: "tech-2",
    type: "technical",
    category: "JavaScript",
    title: "Explain closures in JavaScript",
    description: "What are closures and provide an example of how they are used in JavaScript.",
    answer: "A closure is a function that has access to variables in its outer (enclosing) lexical scope, even after the outer function has returned. Closures are created every time a function is created. For example:\n\nfunction outer() {\n  let count = 0;\n  return function inner() {\n    count++;\n    return count;\n  }\n}\n\nconst counter = outer();\nconsole.log(counter()); // 1\nconsole.log(counter()); // 2\n\nThe inner function maintains access to 'count' even after outer() has finished executing. This is useful for data encapsulation, creating private variables, and implementing patterns like module pattern.",
  },
  {
    id: "tech-3",
    type: "technical",
    category: "Node.js",
    title: "What is event loop in Node.js?",
    description: "Describe the event loop mechanism in Node.js and how it handles asynchronous operations.",
    answer: "The event loop is the core mechanism that allows Node.js to perform non-blocking I/O operations despite JavaScript being single-threaded. It works in phases:\n\n1. Timers: Executes setTimeout/setInterval callbacks\n2. Pending callbacks: Executes I/O callbacks deferred to next loop\n3. Idle/prepare: Internal use only\n4. Poll: Retrieves new I/O events\n5. Check: Executes setImmediate() callbacks\n6. Close callbacks: Executes close event callbacks\n\nWhen async operations complete, their callbacks are added to the appropriate queue. The event loop continuously checks these queues and executes callbacks when the call stack is empty. This allows Node.js to handle thousands of concurrent connections efficiently without creating new threads for each operation.",
  },
  {
    id: "tech-4",
    type: "technical",
    category: "Python",
    title: "Difference between list and tuple",
    description: "Explain the key differences between lists and tuples in Python.",
    answer: "Lists and tuples are both sequence data types in Python, but have key differences:\n\n1. Mutability: Lists are mutable (can be modified), tuples are immutable (cannot be changed after creation)\n2. Syntax: Lists use square brackets [], tuples use parentheses ()\n3. Performance: Tuples are slightly faster and use less memory\n4. Methods: Lists have more built-in methods (append, remove, etc.)\n5. Use cases: Lists for collections that change; tuples for fixed data like coordinates, function return values\n\nExample:\nmy_list = [1, 2, 3]\nmy_list[0] = 10  # OK\n\nmy_tuple = (1, 2, 3)\nmy_tuple[0] = 10  # Error!\n\nTuples can be used as dictionary keys because they're immutable, while lists cannot.",
  },
   {
    id: "tech-5",
    type: "technical",
    category: "Python",
    title: "Difference between list and tuple",
    description: "Explain the key differences between lists and tuples in Python.",
    answer: "Lists and tuples are both sequence data types in Python, but have key differences:\n\n1. Mutability: Lists are mutable (can be modified), tuples are immutable (cannot be changed after creation)\n2. Syntax: Lists use square brackets [], tuples use parentheses ()\n3. Performance: Tuples are slightly faster and use less memory\n4. Methods: Lists have more built-in methods (append, remove, etc.)\n5. Use cases: Lists for collections that change; tuples for fixed data like coordinates, function return values\n\nExample:\nmy_list = [1, 2, 3]\nmy_list[0] = 10  # OK\n\nmy_tuple = (1, 2, 3)\nmy_tuple[0] = 10  # Error!\n\nTuples can be used as dictionary keys because they're immutable, while lists cannot.",
  },
   {
    id: "tech-6",
    type: "technical",
    category: "Python",
    title: "Difference between list and tuple",
    description: "Explain the key differences between lists and tuples in Python.",
    answer: "Lists and tuples are both sequence data types in Python, but have key differences:\n\n1. Mutability: Lists are mutable (can be modified), tuples are immutable (cannot be changed after creation)\n2. Syntax: Lists use square brackets [], tuples use parentheses ()\n3. Performance: Tuples are slightly faster and use less memory\n4. Methods: Lists have more built-in methods (append, remove, etc.)\n5. Use cases: Lists for collections that change; tuples for fixed data like coordinates, function return values\n\nExample:\nmy_list = [1, 2, 3]\nmy_list[0] = 10  # OK\n\nmy_tuple = (1, 2, 3)\nmy_tuple[0] = 10  # Error!\n\nTuples can be used as dictionary keys because they're immutable, while lists cannot.",
  },
   {
    id: "tech-7",
    type: "technical",
    category: "Python",
    title: "Difference between list and tuple",
    description: "Explain the key differences between lists and tuples in Python.",
    answer: "Lists and tuples are both sequence data types in Python, but have key differences:\n\n1. Mutability: Lists are mutable (can be modified), tuples are immutable (cannot be changed after creation)\n2. Syntax: Lists use square brackets [], tuples use parentheses ()\n3. Performance: Tuples are slightly faster and use less memory\n4. Methods: Lists have more built-in methods (append, remove, etc.)\n5. Use cases: Lists for collections that change; tuples for fixed data like coordinates, function return values\n\nExample:\nmy_list = [1, 2, 3]\nmy_list[0] = 10  # OK\n\nmy_tuple = (1, 2, 3)\nmy_tuple[0] = 10  # Error!\n\nTuples can be used as dictionary keys because they're immutable, while lists cannot.",
  },
   {
    id: "tech-8",
    type: "technical",
    category: "Python",
    title: "Difference between list and tuple",
    description: "Explain the key differences between lists and tuples in Python.",
    answer: "Lists and tuples are both sequence data types in Python, but have key differences:\n\n1. Mutability: Lists are mutable (can be modified), tuples are immutable (cannot be changed after creation)\n2. Syntax: Lists use square brackets [], tuples use parentheses ()\n3. Performance: Tuples are slightly faster and use less memory\n4. Methods: Lists have more built-in methods (append, remove, etc.)\n5. Use cases: Lists for collections that change; tuples for fixed data like coordinates, function return values\n\nExample:\nmy_list = [1, 2, 3]\nmy_list[0] = 10  # OK\n\nmy_tuple = (1, 2, 3)\nmy_tuple[0] = 10  # Error!\n\nTuples can be used as dictionary keys because they're immutable, while lists cannot.",
  },
   {
    id: "tech-9",
    type: "technical",
    category: "Python",
    title: "Difference between list and tuple",
    description: "Explain the key differences between lists and tuples in Python.",
    answer: "Lists and tuples are both sequence data types in Python, but have key differences:\n\n1. Mutability: Lists are mutable (can be modified), tuples are immutable (cannot be changed after creation)\n2. Syntax: Lists use square brackets [], tuples use parentheses ()\n3. Performance: Tuples are slightly faster and use less memory\n4. Methods: Lists have more built-in methods (append, remove, etc.)\n5. Use cases: Lists for collections that change; tuples for fixed data like coordinates, function return values\n\nExample:\nmy_list = [1, 2, 3]\nmy_list[0] = 10  # OK\n\nmy_tuple = (1, 2, 3)\nmy_tuple[0] = 10  # Error!\n\nTuples can be used as dictionary keys because they're immutable, while lists cannot.",
  },
  {
    id: "tech-5",
    type: "technical",
    category: "Database",
    title: "SQL vs NoSQL databases",
    description: "Compare and contrast SQL and NoSQL databases, and when to use each.",
    answer: "SQL (Relational) vs NoSQL databases:\n\nSQL Databases:\n- Structured, table-based with predefined schema\n- ACID compliance (Atomicity, Consistency, Isolation, Durability)\n- Strong relationships between tables via foreign keys\n- Best for: Complex queries, transactions, structured data\n- Examples: PostgreSQL, MySQL, Oracle\n\nNoSQL Databases:\n- Flexible schema, various data models (document, key-value, graph, column-family)\n- Eventually consistent (BASE model)\n- Horizontal scalability\n- Best for: Big data, real-time applications, unstructured data\n- Examples: MongoDB, Redis, Cassandra\n\nUse SQL when you need strong consistency, complex joins, and well-defined relationships. Use NoSQL for rapid development, massive scale, flexible data models, or when data structure varies.",
  },
  {
    id: "hr-1",
    type: "hr",
    category: "Behavioral",
    title: "Tell me about yourself",
    description: "Provide a brief introduction about your background, skills, and career goals.",
    answer: "A good response should follow this structure:\n\n1. Present: Current role and key responsibilities\n2. Past: Relevant experience and achievements\n3. Future: Why you're interested in this position\n\nExample: 'I'm currently a full-stack developer with 3 years of experience specializing in React and Node.js. I've led the development of several enterprise applications that serve over 100,000 users. Previously, I worked at a startup where I built features from scratch and learned to work in fast-paced environments. I'm particularly drawn to this role because it offers the opportunity to work on cutting-edge technology while making a meaningful impact on users' lives. I'm passionate about creating elegant solutions to complex problems and continuously learning new technologies.'",
  },
  {
    id: "hr-2",
    type: "hr",
    category: "Behavioral",
    title: "Why do you want to work here?",
    description: "Explain your motivation for applying to this company and what attracts you to this role.",
    answer: "Structure your answer around:\n\n1. Company-specific reasons (mission, culture, products)\n2. Role alignment with your skills and interests\n3. Growth opportunities\n\nExample: 'I'm excited about this opportunity for three reasons. First, your company's mission to democratize access to technology aligns with my personal values. I've been following your product launches and am impressed by your commitment to innovation. Second, this role combines my technical expertise with my interest in scalable systems, which is exactly the direction I want to grow in. Finally, your company's reputation for investing in employee development and fostering a collaborative culture matches what I'm looking for in my next opportunity. I believe I can contribute meaningfully while continuing to grow professionally.'",
  },
  {
    id: "hr-3",
    type: "hr",
    category: "Behavioral",
    title: "Describe a challenging project",
    description: "Share an example of a difficult project you worked on and how you overcame the challenges.",
    answer: "Use the STAR method (Situation, Task, Action, Result):\n\nSituation: 'Our team was tasked with migrating a legacy monolith to microservices while maintaining zero downtime for 500,000 daily active users.'\n\nTask: 'I was responsible for redesigning the authentication system and ensuring data consistency during the transition.'\n\nAction: 'I implemented a strangler pattern, created a feature flag system, and built comprehensive monitoring. I collaborated with the DevOps team to set up blue-green deployments and wrote extensive integration tests.'\n\nResult: 'We successfully completed the migration in 6 months with zero downtime. The new system improved response times by 40% and reduced infrastructure costs by 30%. This experience taught me the importance of incremental changes and robust testing in large-scale migrations.'",
  },
  {
    id: "hr-4",
    type: "hr",
    category: "Situational",
    title: "How do you handle conflicts?",
    description: "Describe your approach to resolving conflicts with team members.",
    answer: "A strong answer demonstrates emotional intelligence and problem-solving:\n\n'I believe conflicts often arise from miscommunication or different perspectives, both of which can be valuable. My approach is:\n\n1. Listen actively to understand the other person's viewpoint without interrupting\n2. Ask clarifying questions to ensure I fully understand their concerns\n3. Find common ground and shared goals\n4. Propose solutions that address both parties' needs\n5. Follow up to ensure the resolution worked\n\nFor example, I once disagreed with a colleague about architecture decisions. Instead of debating, I suggested we each document our approaches with pros/cons, then present to the team. This revealed that combining elements from both approaches created the best solution. The experience strengthened our working relationship and taught me that conflicts can drive better outcomes when handled constructively.'",
  },
  {
    id: "hr-5",
    type: "hr",
    category: "Career",
    title: "Where do you see yourself in 5 years?",
    description: "Discuss your long-term career aspirations and goals.",
    answer: "Balance ambition with realism and company alignment:\n\n'In five years, I see myself having grown into a senior technical role where I'm not only contributing high-quality code but also mentoring junior developers and influencing architectural decisions. I'm particularly interested in deepening my expertise in distributed systems and potentially moving into a technical lead position.\n\nI'm also committed to continuous learning—I plan to contribute more to open source, speak at conferences, and stay current with emerging technologies. However, I'm flexible about the exact path, as I believe the best careers evolve organically through opportunities and experiences.\n\nWhat excites me about this company is that you seem to invest in your employees' growth and provide opportunities to take on increasing responsibility. I'd love to grow alongside the company and potentially take on leadership roles as they align with both my development and organizational needs.'",
  },
  {
    id: "code-1",
    type: "coding",
    category: "Arrays",
    title: "Two Sum",
    description: "Given an array of integers nums and an integer target, return indices of the two numbers that add up to target.",
    difficulty: "easy",
    answer: "Solution using hash map for O(n) time complexity:\n\n```python\ndef twoSum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[num] = i\n    return []\n```\n\nTime Complexity: O(n) - single pass through array\nSpace Complexity: O(n) - hash map storage\n\nExplanation: We iterate through the array once. For each number, we calculate what value we'd need to reach the target (complement). If we've seen that complement before, we found our pair. Otherwise, we store the current number and its index for future reference.",
  },
  {
    id: "code-2",
    type: "coding",
    category: "Strings",
    title: "Valid Palindrome",
    description: "Given a string s, determine if it is a palindrome, considering only alphanumeric characters and ignoring cases.",
    difficulty: "easy",
    answer: "Two-pointer approach:\n\n```python\ndef isPalindrome(s):\n    left, right = 0, len(s) - 1\n    \n    while left < right:\n        while left < right and not s[left].isalnum():\n            left += 1\n        while left < right and not s[right].isalnum():\n            right -= 1\n        \n        if s[left].lower() != s[right].lower():\n            return False\n        \n        left += 1\n        right -= 1\n    \n    return True\n```\n\nTime Complexity: O(n)\nSpace Complexity: O(1)\n\nWe use two pointers starting from both ends, skipping non-alphanumeric characters and comparing characters case-insensitively.",
  },
  {
    id: "code-3",
    type: "coding",
    category: "Linked List",
    title: "Reverse Linked List",
    description: "Given the head of a singly linked list, reverse the list and return the reversed list.",
    difficulty: "medium",
    answer: "Iterative solution:\n\n```python\ndef reverseList(head):\n    prev = None\n    current = head\n    \n    while current:\n        next_node = current.next\n        current.next = prev\n        prev = current\n        current = next_node\n    \n    return prev\n```\n\nTime Complexity: O(n)\nSpace Complexity: O(1)\n\nWe iterate through the list, reversing the direction of each pointer. We maintain three pointers: previous, current, and next. At each step, we reverse the current node's pointer to point to the previous node.",
  },
  {
    id: "code-4",
    type: "coding",
    category: "Trees",
    title: "Binary Tree Maximum Depth",
    description: "Given the root of a binary tree, return its maximum depth.",
    difficulty: "easy",
    answer: "Recursive DFS solution:\n\n```python\ndef maxDepth(root):\n    if not root:\n        return 0\n    \n    left_depth = maxDepth(root.left)\n    right_depth = maxDepth(root.right)\n    \n    return max(left_depth, right_depth) + 1\n```\n\nTime Complexity: O(n) - visit each node once\nSpace Complexity: O(h) - recursion stack, where h is height\n\nThe maximum depth is the maximum of the depths of the left and right subtrees, plus 1 for the current node. Base case: empty tree has depth 0.",
  },
  {
    id: "code-5",
    type: "coding",
    category: "Dynamic Programming",
    title: "Climbing Stairs",
    description: "You are climbing a staircase. It takes n steps to reach the top. Each time you can climb 1 or 2 steps. How many ways can you climb to the top?",
    difficulty: "medium",
    answer: "Dynamic Programming solution:\n\n```python\ndef climbStairs(n):\n    if n <= 2:\n        return n\n    \n    prev2, prev1 = 1, 2\n    \n    for i in range(3, n + 1):\n        current = prev1 + prev2\n        prev2 = prev1\n        prev1 = current\n    \n    return prev1\n```\n\nTime Complexity: O(n)\nSpace Complexity: O(1)\n\nThis is essentially a Fibonacci sequence. To reach step n, you can either come from step n-1 (1 step) or step n-2 (2 steps). So ways(n) = ways(n-1) + ways(n-2). We optimize space by only keeping track of the last two values instead of an entire array.",
  },
];
